### ISSUE TITLE
Is this plugin being supported?

### ISSUE THREAD

**Issue by tom-byrom** [blue-mantis/craft-private-messaging#1]
Hello guys,
I've been looking for a messaging plugin for Craft - this one was hard to find but looks like the only one available! 

Are you supporting this? I see it's not available through the plugin store so just wanted to see if it's going to be supported before using it.

Thanks
Tom

**Comment by auralon** [comment]
@tom-byrom I received your email and have responded via email also.  Let me know if I can be of any further assistance.
